version: "3.7"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management-alpine
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/logs/:/var/log/rabbitmq/    
    ports:
      - 5672:5672 #queue
      - 15672:15672 #management